fix(core): :bug: corelistitem validvalues are not in array
wrappid/core pull request #329
Opened 2024-08-26 11:00 UTC by arkaprota

## Description

the requirement to put the validvalues are in array

Ref: #328

2024-08-27 14:35 UTC, techoneel requested changes
Please see the changes and give your reference to this.

2024-08-27 14:35 UTC, techoneel commented on package/components/dataDisplay/CoreListItem.js
> +        validValues: ["{ root?: elementType }"]
valid values are wrongly placed.

2024-08-29 06:38 UTC, arkaprota commented
please check if there is any changes required or not
@techoneel

2024-08-30 05:46 UTC, arkaprota commented on package/components/dataDisplay/CoreListItem.js
> +        validValues: ["{ root?: elementType }"]
validvalues are removed please let me know if there is any changes needed or not
@techoneel

2024-09-04 06:57 UTC, techoneel approved these changes
good to go

2024-09-04 06:58 UTC, merged