bugifix: dataDisplay/CoreTable related CoreComponents prop sanitization
wrappid/core pull request #339
Opened 2024-08-28 11:16 UTC by anantakumarghosh

## Description

Clearly describe the changes you've made in this pull request. Explain the purpose and reasoning behind the changes. Reference any relevant issues or discussions using keywords like "Fixes #<issue_number>" or "Resolves #<issue_number>".

## Related Issues

## Testing

## Checklist

- [ ] I have performed a thorough self-review of my code.
- [ ] I have added or updated relevant tests for my changes.
- [ ] My code follows the project's style guidelines and best practices.
- [ ] I have updated the documentation if necessary.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts of my branch.

## Screenshots (if applicable)

## Additional Notes

## Reviewers

---

## Maintainer Notes

- [ ] Has this change been tested in a staging environment?
- [ ] Does this change introduce any breaking changes or deprecations?

2024-08-29 04:32 UTC, techoneel requested changes
Please do the following changes:

1. Remove unnecessary destructure
2. Self closing tag
3. component default value can be removed if problem appears then put it inside default value

2024-08-29 04:32 UTC, techoneel commented on package/components/dataDisplay/CoreTable.js
> +    <NativeTable
Unnecessary props destructure.

2024-08-29 04:32 UTC, techoneel commented on package/components/dataDisplay/CoreTableBody.js
> +  return <NativeTableBody {...props}>{props?.children}</NativeTableBody>;
Can be self closing.

2024-08-29 04:32 UTC, techoneel commented on package/components/dataDisplay/CoreTableContainer.js
> +  return <NativeTableContainer {...props}>{props?.children}</NativeTableContainer>;
Can be self closing

2024-08-29 04:32 UTC, techoneel commented on package/components/dataDisplay/CoreTableFooter.js
> +  return <NativeTableFooter {...props}>{props?.children}</NativeTableFooter>;
Can be self closing

2024-08-29 04:32 UTC, techoneel commented on package/components/dataDisplay/CoreTablePagination.js
>      <NativeTablePagination
Need to remove and check component div

2024-08-29 18:23 UTC, techoneel requested changes, later dismissed
please do the needed changes or added todo

2024-08-29 18:23 UTC, techoneel commented on package/components/dataDisplay/CoreTable.js
> -  let _uuid = getUUID();
do not remove this code else comment it for future use or create a todo

2024-08-30 05:56 UTC, anantakumarghosh commented on package/components/dataDisplay/CoreTable.js
> -  let _uuid = getUUID();
> do not remove this code else comment it for future use or create a todo

Removed as it was not being used, and there is no "todo".

Please tell me why it is required and what is the "todo"?

2024-09-04 07:12 UTC, techoneel approved these changes
good to go

2024-09-04 07:12 UTC, merged