feat(global): :sparkles: fix CoreDateRangepicker
wrappid/core pull request #345
Opened 2024-08-31 07:54 UTC by PritamIT2023

fix CoreDateRangepicker

Ref: #344

## Description

Clearly describe the changes you've made in this pull request. Explain the purpose and reasoning behind the changes. Reference any relevant issues or discussions using keywords like "Fixes #<issue_number>" or "Resolves #<issue_number>".

## Related Issues

## Testing

## Checklist

- [ ] I have performed a thorough self-review of my code.
- [ ] I have added or updated relevant tests for my changes.
- [ ] My code follows the project's style guidelines and best practices.
- [ ] I have updated the documentation if necessary.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts of my branch.

## Screenshots (if applicable)

## Additional Notes

## Reviewers

---

## Maintainer Notes

- [ ] Has this change been tested in a staging environment?
- [ ] Does this change introduce any breaking changes or deprecations?

2024-09-04 07:32 UTC, techoneel requested changes
add formik in valid props
remove unnecessary CoreBox

2024-09-04 07:32 UTC, techoneel commented on package/components/inputs/CoreDateRangepicker.js
>      <CoreBox>
remove CoreBox

2024-09-04 10:21 UTC, PritamIT2023 commented on package/components/inputs/CoreDateRangepicker.js
>      <CoreBox>
Done

2024-09-05 09:19 UTC, techoneel approved these changes
Good to go

2024-09-05 09:19 UTC, merged